name: Where

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  #schedule:
  #  - cron: '0 16 4-31/4 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Where
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Find out where
        if: runner.os == 'Windows'
        run: |
          $env:Path += ";C:\Program Files\Git\usr\bin;C:\Program Files\Git\bin"
          where.exe bash && where.exe grep && where.exe sed && where.exe awk && where.exe make && where.exe git
